# docker-compose

version: '3'

services:
  db_postgres:
    image: postgres:13.3-alpine
    container_name: DB_OLYLIFE
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../postgresql_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - network_backend

  node-server:
    container_name: node
    restart: always
    build: .
    env_file:
      - /.env
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
    volumes:
      - ./src:/app/src
    command: ["npm", "run", "start:dev"]
    networks:
      - network_backend

networks:
  network_backend:
    driver: bridge
    ipam:
      driver: default

  